### ISSUE TITLE
Parsing a file of size X can take up to 50X heap space

### ISSUE THREAD

**Issue by dmbaturin** [aantron/lambdasoup#47] opened 2022-02-04 12:16 UTC
I discovered that lambdasoup/markup.ml takes many times more heap space to parse a file than the file size. Consider a trivial test program:

```ocaml
let src = Soup.read_file (Sys.argv.(1))

let soup = Soup.parse src 
```

This is a valgrind/massif report for parsing soupault's reference manual. The manual file is 174Kbytes, but it takes 10Mbytes of heap space to parse. That's tolerable.

![Screenshot at 2022-02-04 18-45-12](https://user-images.githubusercontent.com/482212/152523750-743e7e14-5dfb-47eb-aa0e-56207a7a99a5.png)

With larger files it gets progressively worse. Parsing a 14MB file requires almost **600MB** (45 times the size of the file) of memory allocations. 

![Screenshot at 2022-02-04 18-49-21](https://user-images.githubusercontent.com/482212/152524398-2f6d3a57-d4c7-49e6-be4f-deba2faffd21.png)

That is enough to cause a small CI worker to run out of memory and fail the build. That's how I discovered the issue: a soupault user reported OOM on a VM with 1G RAM when trying to process a 13M large auto-generated file. It's sure an extreme case, but not an invalid one.

From my memtrace profiling, it looks like the cause is that heavy use of CPS creates lots of unreachable allocations faster than the GC can clean up after it.

![Screenshot 2022-02-04 at 19-11-27 Screenshot](https://user-images.githubusercontent.com/482212/152527214-d63a9ed7-a7d5-4866-8c38-74bc94881ed2.png)

Do you think anything can be done to keep the allocation rate lower?

I've attached the memtrace.

[trace.ctf.gz](https://github.com/aantron/lambdasoup/files/8002857/trace.ctf.gz)

**Comment by aantron** [comment] 2022-02-04 13:08
Do you have a ready example of 13MB input, or instructions for generating it?

I'm not familiar with the output of either tool. What is being shown here? Is valgrind showing process heap usage, in terms of how much heap space has been requested from the kernel? The C heap usage? The OCaml heap usage? Would we see OCaml garbage collection in valgrind output?

The graph in the memtrace output has no label on the Y axis. Beneath, it says "allocations" in a sentence. Is it showing heap usage at each point, or allocations performed so far? I assume the former, since the curve sometimes goes down. This would suggest a memory leak.

**Comment by aantron** [comment] 2022-02-04 13:11
> The manual file is 174Kbytes, but it takes 10Mbytes of heap space to parse.

Have you confirmed that it takes 10MB of space to *parse*? Try running the file through Markup.ml only, and seeing it if it takes that much space. It could simply be that the memory represenation of the DOM in Lambda Soup takes 10MB (which may still be a problem).

**Comment by aantron** [comment] 2022-02-04 13:13
The reason for my second comment is that we did use spacetime to look for memory leaks in Markup.ml, and we could easily see the sawtooth pattern of GC collecting memory. This means that either you've found a pathological case with a memory leak, or the graphs above are showing the memory consumption of the Lambda Soup tree being built up.

**Comment by dmbaturin** [comment] 2022-02-04 13:28
>Have you confirmed that it takes 10MB of space to parse?

You are right! Parsing as such (`open_in Sys.argv.(1) |> Markup.channel |> Markup.parse_html |> Markup.signals`) only takes about 4MB. But adding `Soup.from_signals` makes the memory consumption of the test program jump to ~600MB.

>Do you have a ready example of 13MB input, or instructions for generating it?

I've attached the file in question.
[13M.html.gz](https://github.com/aantron/lambdasoup/files/8003256/13M.html.gz)

> Is valgrind showing process heap usage, in terms of how much heap space has been requested from the kernel?

Yes, to my understanding, that's heap space requested from the kernel.

>Is it showing heap usage at each point, or allocations performed so far?

That memtrace plot shows allocations that are live at a certain point. 

> I assume the former, since the curve sometimes goes down. This would suggest a memory leak.

From a real soupault run I could see that the memory usage goes down by orders of magnitude when it finishes processing the 13M page and goes on to smaller pages. So it's not a leak as such (the memory isn't becoming _permanently_ allocated).

**Comment by aantron** [comment] 2022-02-04 13:49
> `open_in Sys.argv.(1) |> Markup.channel |> Markup.parse_html |> Markup.signals`

Could you more fully confirm this by draining the stream using `Markup.drain`?



> From a real soupault run I could see that the memory usage goes down by orders of magnitude when it finishes processing the 13M page and goes on to smaller pages.

Is that after you drop the reference to the DOM produced for the first, large page? There might still be effectively a memory leak within a big object graph (i.e. a bunch of unnecessary memory somehow retained).

**Comment by aantron** [comment] 2022-02-04 13:58
What does `Obj.reachable_words` return for the DOM you get?

**Comment by aantron** [comment] 2022-02-04 14:05
Eyeballing the file and the current Lambda Soup element representation, I expect about ~10x blowup in size for each `<span>` tag in the DOM version relative to its HTML form. The text nodes have less of a blowup. This can be optimized, but it wouldn't explain a 50x blowup.

**Comment by dmbaturin** [comment] 2022-02-04 14:06
>Could you more fully confirm this by draining the stream using Markup.drain?

Interesting! It looks like calling `Markup.drain` reclaims all that memory and solves the problem. I'm going to run more tests and get back to you.

**Comment by aantron** [comment] 2022-02-04 14:10
I recommend also passing the `~report` argument to `parse_html` and printing any errors:

```ocaml
~report:(fun location error -> Markup.Error.to_string ~location error |> print_endline)
```

just in case the issue is that Markup.ml is struggling in some error-recovery state from ill-formed HTML somewhere (unlikely, given you tried two different kinds of inputs).

**Comment by dmbaturin** [comment] 2022-02-04 14:47
Wait, I completely misunderstood the purpose of `Markup.drain`. The point stands: adding `Markup.channel |> Markup.drain` doesn't consume 600MB of RAM while processing that file.

But changing adding `Soup.from_signals` consumes all that RAM.

This is the latest version of the test program.

```ocaml
let _ = 
  let chan = open_in Sys.argv.(1) |> Markup.channel in
  let signals = Markup.parse_html chan |> Markup.signals in
  let s = Soup.from_signals signals in
  let () = Gc.full_major () in
  Printf.printf "Reachable words: %d" (Obj.reachable_words @@ Obj.repr s)
```

The output is: `Reachable words: 24033120`.

**Comment by aantron** [comment] 2022-02-04 18:23
> The output is: `Reachable words: 24033120`.

That implies that the Lambda Soup DOM is about 190MB in size. Are there close to 24M live words at this point?

**Comment by aantron** [comment] 2022-02-04 18:28
I also just realized that for single-character text nodes, the size blowup is about 80x relative to their in-file representation, due to all the overhead. The 13M file has a lot of text nodes containing only `/`. I wonder if `Obj.reachable_words` counts the words used by the content of strings. In any case, this ratio might partially explain the 50x overall blowup.

**Comment by aantron** [comment] 2022-02-04 18:31
> `Markup.channel |> Markup.drain`

Do you literally draining the character stream returned by `Markup.channel`? Or did you actually do

```
Markup.channel |> Markup.parse_html |> Markup.signals |> Markup.drain
```

i.e. actually run the parser and drain the signal stream?

**Comment by dmbaturin** [comment] 2022-02-04 18:38
>Or did you actually do `Markup.channel |> Markup.parse_html |> Markup.signals |> Markup.drain`

Sorry, I think the first time I did it wrong indeed! I've just done `Markup.channel |> Markup.parse_html |> Markup.signals |> Markup.drain` and that took about 350M RAM. 350M for the parsing and 190 for the DOM, that seems to add up to the original RAM usage figure (more or less).

Also, that page seems nearly impossible to open in browser in practice, so I think the issue is mostly academic. Usable pages consume sane amounts of RAM, and pages that cause troubles don't seem usable. But I'm still curious if it could use less.

**Comment by aantron** [comment] 2022-02-04 19:46
It's definitely possible to reduce the memory consumption of the DOM by at least a constant factor, like 2x or 1.5x. If willing to do more extensive and invasive optimizations, it could be possible to really reduce usage greatly.

I am concerned about the 350M for parsing. The parser should be able to "retire" most blocks from memory. I assume that GC isn't running during the parse &mdash; is that correct? Then it seems plausible. However, then I am concerned that in your user's VM, the OCaml runtime didn't force a garbage collection (or did it, and it was only the DOM part of the memory usage, which isn't eligible for collection, that caused the OOM?)

**Comment by aantron** [comment] 2022-02-04 19:48
> Also, that page seems nearly impossible to open in browser in practice

It's good to hear. I've generally found that Markup.ml (and Lambda Soup) have the same behavior as browsers, including error recovery, etc., so it's nice to hear that huge page behavior is if not the same, at least similarly unacceptable between both :) But as noted above, it's likely possible to improve Markup.ml and/or Lambda Soup with some ease to do a bit better.

**Comment by aantron** [comment] 2022-02-07 18:18
As of now, I think:

- Lambda Soup memory usage can easily be reduced by removing the `self` field. A slightly tricker change is inlining the text field, and using it for both text node content and element names. That should save some block headers.
- We could hash-cons the string values of text nodes and element names to reuse many blocks.
- A more involved change is changing the DOM so that text nodes do not explicitly store parent pointers. This would make many nodes in the input such as this 13M input structurally identical, since they would no longer differ in just having different parents. Hash-consing could then be applied to the whole text nodes (rather than just the string payloads). The `node` returned from the surface Lambda Soup API would then have to be, if it is a text node, a pair of a parent node pointer and the pointer to the text node in the DOM.
- I'm concerned about the above comments which suggest that the Lambda Soup DOM was only 1/3 of the memory consumption, and I'm not clear if you mean or fully checked whether the other 2/3 that arose in Markup.ml during parsing were eligible for GC or actually triggered the user's OOM. If the real problem is those 2/3, then it's probably best to focus on addressing the 2/3 before changing the Lambda Soup representation too much.
- From your comments above, it appears to me that your user has abandoned this input, or that we have. In that case, maybe we won't do anything...

**Comment by aantron** [comment] 2022-02-07 18:20
> * We could hash-cons the string values of text nodes and element names to reuse many blocks.

(also known as string pooling)

**Comment by dmbaturin** [comment] 2022-02-07 18:30
>I'm not clear if you mean or fully checked whether the other 2/3 that arose in Markup.ml during parsing were eligible for GC or actually triggered the user's OOM

I'll try to do more detailed tests to confirm that.

>From your comments above, it appears to me that your user has abandoned this input

The user has abandoned it I think. I also confirmed that GitHub _refuses_ to display that file in the web UI and only offers an option to downloaded it raw.

So, while it definitely would be cool to make LambdaSoup/Markup.ml handle very large inputs faster than browsers, it will not help anyone actually view absurdly large files on the web and it may indeed be a wasted effort.

**Comment by aantron** [comment] 2024-07-25 05:48
I'm going to close this issue since we looked into it, but it doesn't look like there is a need to solve it. We can return and do some optimizations upon future demand. Thank you!

**Closed by aantron** 2024-07-25 05:48 UTC
